name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --passWithNoTests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Google Cloud SDK
#        uses: google-github-actions/setup-gcloud@v0.2.0
#        with:
#          version: 'latest'
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          project_id: ${{ secrets.GCP_PROJECT_ID }}

#      - name: Deploy to Cloud Run
#        run: |
#          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-nestjs-project
#          gcloud run deploy my-nestjs-project --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-nestjs-project --platform managed --region us-central1 --allow-unauthenticated
